// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: RealtimeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRealtimeRepository is a mock of RealtimeRepository interface.
type MockRealtimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRealtimeRepositoryMockRecorder
}

// MockRealtimeRepositoryMockRecorder is the mock recorder for MockRealtimeRepository.
type MockRealtimeRepositoryMockRecorder struct {
	mock *MockRealtimeRepository
}

// NewMockRealtimeRepository creates a new mock instance.
func NewMockRealtimeRepository(ctrl *gomock.Controller) *MockRealtimeRepository {
	mock := &MockRealtimeRepository{ctrl: ctrl}
	mock.recorder = &MockRealtimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealtimeRepository) EXPECT() *MockRealtimeRepositoryMockRecorder {
	return m.recorder
}

// AppendEvent mocks base method.
func (m *MockRealtimeRepository) AppendEvent(arg0 context.Context, arg1 string, arg2 domain.EventEnvelope, arg3 time.Time) (domain.EventAppendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(domain.EventAppendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockRealtimeRepositoryMockRecorder) AppendEvent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockRealtimeRepository)(nil).AppendEvent), arg0, arg1, arg2, arg3)
}

// ClaimInbox mocks base method.
func (m *MockRealtimeRepository) ClaimInbox(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 uuid.UUID, arg5 time.Time, arg6 time.Duration) (domain.InboxClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimInbox", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(domain.InboxClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimInbox indicates an expected call of ClaimInbox.
func (mr *MockRealtimeRepositoryMockRecorder) ClaimInbox(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimInbox", reflect.TypeOf((*MockRealtimeRepository)(nil).ClaimInbox), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// ClaimOutbox mocks base method.
func (m *MockRealtimeRepository) ClaimOutbox(arg0 context.Context, arg1, arg2 string, arg3 time.Time, arg4 time.Duration, arg5 int) ([]domain.OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOutbox", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]domain.OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOutbox indicates an expected call of ClaimOutbox.
func (mr *MockRealtimeRepositoryMockRecorder) ClaimOutbox(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOutbox", reflect.TypeOf((*MockRealtimeRepository)(nil).ClaimOutbox), arg0, arg1, arg2, arg3, arg4, arg5)
}

// CompleteInbox mocks base method.
func (m *MockRealtimeRepository) CompleteInbox(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4, arg5 uuid.UUID, arg6 time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteInbox", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteInbox indicates an expected call of CompleteInbox.
func (mr *MockRealtimeRepositoryMockRecorder) CompleteInbox(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteInbox", reflect.TypeOf((*MockRealtimeRepository)(nil).CompleteInbox), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// GetEvent mocks base method.
func (m *MockRealtimeRepository) GetEvent(arg0 context.Context, arg1 string, arg2 uuid.UUID) (*domain.EventEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.EventEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockRealtimeRepositoryMockRecorder) GetEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockRealtimeRepository)(nil).GetEvent), arg0, arg1, arg2)
}

// ListTriggerBindings mocks base method.
func (m *MockRealtimeRepository) ListTriggerBindings(arg0 context.Context, arg1, arg2, arg3 string) ([]domain.TriggerBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTriggerBindings", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]domain.TriggerBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTriggerBindings indicates an expected call of ListTriggerBindings.
func (mr *MockRealtimeRepositoryMockRecorder) ListTriggerBindings(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTriggerBindings", reflect.TypeOf((*MockRealtimeRepository)(nil).ListTriggerBindings), arg0, arg1, arg2, arg3)
}

// MarkOutboxPublished mocks base method.
func (m *MockRealtimeRepository) MarkOutboxPublished(arg0 context.Context, arg1 string, arg2, arg3 uuid.UUID, arg4 time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxPublished", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOutboxPublished indicates an expected call of MarkOutboxPublished.
func (mr *MockRealtimeRepositoryMockRecorder) MarkOutboxPublished(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxPublished", reflect.TypeOf((*MockRealtimeRepository)(nil).MarkOutboxPublished), arg0, arg1, arg2, arg3, arg4)
}

// ReleaseOutbox mocks base method.
func (m *MockRealtimeRepository) ReleaseOutbox(arg0 context.Context, arg1 string, arg2, arg3 uuid.UUID, arg4 time.Time, arg5 string, arg6 bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseOutbox", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseOutbox indicates an expected call of ReleaseOutbox.
func (mr *MockRealtimeRepositoryMockRecorder) ReleaseOutbox(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseOutbox", reflect.TypeOf((*MockRealtimeRepository)(nil).ReleaseOutbox), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// ReserveSideEffect mocks base method.
func (m *MockRealtimeRepository) ReserveSideEffect(arg0 context.Context, arg1 string, arg2 domain.SideEffectExecution) (domain.SideEffectExecution, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveSideEffect", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.SideEffectExecution)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReserveSideEffect indicates an expected call of ReserveSideEffect.
func (mr *MockRealtimeRepositoryMockRecorder) ReserveSideEffect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveSideEffect", reflect.TypeOf((*MockRealtimeRepository)(nil).ReserveSideEffect), arg0, arg1, arg2)
}

// WriteMatchAudit mocks base method.
func (m *MockRealtimeRepository) WriteMatchAudit(arg0 context.Context, arg1 string, arg2 domain.MatchAudit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMatchAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMatchAudit indicates an expected call of WriteMatchAudit.
func (mr *MockRealtimeRepositoryMockRecorder) WriteMatchAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMatchAudit", reflect.TypeOf((*MockRealtimeRepository)(nil).WriteMatchAudit), arg0, arg1, arg2)
}
