// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: AutomationService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAutomationService is a mock of AutomationService interface.
type MockAutomationService struct {
	ctrl     *gomock.Controller
	recorder *MockAutomationServiceMockRecorder
}

// MockAutomationServiceMockRecorder is the mock recorder for MockAutomationService.
type MockAutomationServiceMockRecorder struct {
	mock *MockAutomationService
}

// NewMockAutomationService creates a new mock instance.
func NewMockAutomationService(ctrl *gomock.Controller) *MockAutomationService {
	mock := &MockAutomationService{ctrl: ctrl}
	mock.recorder = &MockAutomationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutomationService) EXPECT() *MockAutomationServiceMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockAutomationService) Activate(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockAutomationServiceMockRecorder) Activate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockAutomationService)(nil).Activate), arg0, arg1, arg2)
}

// ActivateRealtimePrimary mocks base method.
func (m *MockAutomationService) ActivateRealtimePrimary(arg0 context.Context, arg1 string, arg2, arg3 time.Time) (domain.RealtimeCutoverReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateRealtimePrimary", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(domain.RealtimeCutoverReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateRealtimePrimary indicates an expected call of ActivateRealtimePrimary.
func (mr *MockAutomationServiceMockRecorder) ActivateRealtimePrimary(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateRealtimePrimary", reflect.TypeOf((*MockAutomationService)(nil).ActivateRealtimePrimary), arg0, arg1, arg2, arg3)
}

// AssessRealtimeCutover mocks base method.
func (m *MockAutomationService) AssessRealtimeCutover(arg0 context.Context, arg1 string, arg2, arg3 time.Time) (domain.PrimaryCutoverAssessment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssessRealtimeCutover", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(domain.PrimaryCutoverAssessment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssessRealtimeCutover indicates an expected call of AssessRealtimeCutover.
func (mr *MockAutomationServiceMockRecorder) AssessRealtimeCutover(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssessRealtimeCutover", reflect.TypeOf((*MockAutomationService)(nil).AssessRealtimeCutover), arg0, arg1, arg2, arg3)
}

// Create mocks base method.
func (m *MockAutomationService) Create(arg0 context.Context, arg1 string, arg2 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAutomationServiceMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAutomationService)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockAutomationService) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAutomationServiceMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAutomationService)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockAutomationService) Get(arg0 context.Context, arg1, arg2 string) (*domain.Automation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Automation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAutomationServiceMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAutomationService)(nil).Get), arg0, arg1, arg2)
}

// GetContactNodeExecutions mocks base method.
func (m *MockAutomationService) GetContactNodeExecutions(arg0 context.Context, arg1, arg2, arg3 string) (*domain.ContactAutomation, []*domain.NodeExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactNodeExecutions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.ContactAutomation)
	ret1, _ := ret[1].([]*domain.NodeExecution)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetContactNodeExecutions indicates an expected call of GetContactNodeExecutions.
func (mr *MockAutomationServiceMockRecorder) GetContactNodeExecutions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactNodeExecutions", reflect.TypeOf((*MockAutomationService)(nil).GetContactNodeExecutions), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockAutomationService) List(arg0 context.Context, arg1 string, arg2 domain.AutomationFilter) ([]*domain.Automation, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Automation)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAutomationServiceMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAutomationService)(nil).List), arg0, arg1, arg2)
}

// Pause mocks base method.
func (m *MockAutomationService) Pause(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockAutomationServiceMockRecorder) Pause(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockAutomationService)(nil).Pause), arg0, arg1, arg2)
}

// RestoreRealtimeLegacy mocks base method.
func (m *MockAutomationService) RestoreRealtimeLegacy(arg0 context.Context, arg1 string) (domain.RealtimeCutoverReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreRealtimeLegacy", arg0, arg1)
	ret0, _ := ret[0].(domain.RealtimeCutoverReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreRealtimeLegacy indicates an expected call of RestoreRealtimeLegacy.
func (mr *MockAutomationServiceMockRecorder) RestoreRealtimeLegacy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreRealtimeLegacy", reflect.TypeOf((*MockAutomationService)(nil).RestoreRealtimeLegacy), arg0, arg1)
}

// Update mocks base method.
func (m *MockAutomationService) Update(arg0 context.Context, arg1 string, arg2 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAutomationServiceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAutomationService)(nil).Update), arg0, arg1, arg2)
}
