// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/realtime.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRuleEventProcessor is a mock of RuleEventProcessor interface.
type MockRuleEventProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockRuleEventProcessorMockRecorder
}

// MockRuleEventProcessorMockRecorder is the mock recorder for MockRuleEventProcessor.
type MockRuleEventProcessorMockRecorder struct {
	mock *MockRuleEventProcessor
}

// NewMockRuleEventProcessor creates a new mock instance.
func NewMockRuleEventProcessor(ctrl *gomock.Controller) *MockRuleEventProcessor {
	mock := &MockRuleEventProcessor{ctrl: ctrl}
	mock.recorder = &MockRuleEventProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleEventProcessor) EXPECT() *MockRuleEventProcessorMockRecorder {
	return m.recorder
}

// ProcessRuleEvent mocks base method.
func (m *MockRuleEventProcessor) ProcessRuleEvent(arg0 context.Context, arg1 domain.RuleProcessRequest) (domain.RuleProcessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRuleEvent", arg0, arg1)
	ret0, _ := ret[0].(domain.RuleProcessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRuleEvent indicates an expected call of ProcessRuleEvent.
func (mr *MockRuleEventProcessorMockRecorder) ProcessRuleEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRuleEvent", reflect.TypeOf((*MockRuleEventProcessor)(nil).ProcessRuleEvent), arg0, arg1)
}

// MockRealtimeRepository is a mock of RealtimeRepository interface.
type MockRealtimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRealtimeRepositoryMockRecorder
}

// MockRealtimeRepositoryMockRecorder is the mock recorder for MockRealtimeRepository.
type MockRealtimeRepositoryMockRecorder struct {
	mock *MockRealtimeRepository
}

// NewMockRealtimeRepository creates a new mock instance.
func NewMockRealtimeRepository(ctrl *gomock.Controller) *MockRealtimeRepository {
	mock := &MockRealtimeRepository{ctrl: ctrl}
	mock.recorder = &MockRealtimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealtimeRepository) EXPECT() *MockRealtimeRepositoryMockRecorder {
	return m.recorder
}

// AppendEvent mocks base method.
func (m *MockRealtimeRepository) AppendEvent(ctx context.Context, workspaceID string, envelope domain.EventEnvelope, receivedAt time.Time) (domain.EventAppendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", ctx, workspaceID, envelope, receivedAt)
	ret0, _ := ret[0].(domain.EventAppendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockRealtimeRepositoryMockRecorder) AppendEvent(ctx, workspaceID, envelope, receivedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockRealtimeRepository)(nil).AppendEvent), ctx, workspaceID, envelope, receivedAt)
}

// ClaimInbox mocks base method.
func (m *MockRealtimeRepository) ClaimInbox(ctx context.Context, tx *sql.Tx, workspaceID, consumer string, messageID uuid.UUID, now time.Time, lease time.Duration) (domain.InboxClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimInbox", ctx, tx, workspaceID, consumer, messageID, now, lease)
	ret0, _ := ret[0].(domain.InboxClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimInbox indicates an expected call of ClaimInbox.
func (mr *MockRealtimeRepositoryMockRecorder) ClaimInbox(ctx, tx, workspaceID, consumer, messageID, now, lease interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimInbox", reflect.TypeOf((*MockRealtimeRepository)(nil).ClaimInbox), ctx, tx, workspaceID, consumer, messageID, now, lease)
}

// ClaimOutbox mocks base method.
func (m *MockRealtimeRepository) ClaimOutbox(ctx context.Context, workspaceID, workerID string, now time.Time, lease time.Duration, limit int) ([]domain.OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOutbox", ctx, workspaceID, workerID, now, lease, limit)
	ret0, _ := ret[0].([]domain.OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOutbox indicates an expected call of ClaimOutbox.
func (mr *MockRealtimeRepositoryMockRecorder) ClaimOutbox(ctx, workspaceID, workerID, now, lease, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOutbox", reflect.TypeOf((*MockRealtimeRepository)(nil).ClaimOutbox), ctx, workspaceID, workerID, now, lease, limit)
}

// CompleteInbox mocks base method.
func (m *MockRealtimeRepository) CompleteInbox(ctx context.Context, tx *sql.Tx, workspaceID, consumer string, messageID, claimToken uuid.UUID, completedAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteInbox", ctx, tx, workspaceID, consumer, messageID, claimToken, completedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteInbox indicates an expected call of CompleteInbox.
func (mr *MockRealtimeRepositoryMockRecorder) CompleteInbox(ctx, tx, workspaceID, consumer, messageID, claimToken, completedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteInbox", reflect.TypeOf((*MockRealtimeRepository)(nil).CompleteInbox), ctx, tx, workspaceID, consumer, messageID, claimToken, completedAt)
}

// DeleteTriggerBindings mocks base method.
func (m *MockRealtimeRepository) DeleteTriggerBindings(ctx context.Context, workspaceID, automationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTriggerBindings", ctx, workspaceID, automationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTriggerBindings indicates an expected call of DeleteTriggerBindings.
func (mr *MockRealtimeRepositoryMockRecorder) DeleteTriggerBindings(ctx, workspaceID, automationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTriggerBindings", reflect.TypeOf((*MockRealtimeRepository)(nil).DeleteTriggerBindings), ctx, workspaceID, automationID)
}

// GetEvent mocks base method.
func (m *MockRealtimeRepository) GetEvent(ctx context.Context, workspaceID string, eventID uuid.UUID) (*domain.EventEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, workspaceID, eventID)
	ret0, _ := ret[0].(*domain.EventEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockRealtimeRepositoryMockRecorder) GetEvent(ctx, workspaceID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockRealtimeRepository)(nil).GetEvent), ctx, workspaceID, eventID)
}

// ListTriggerBindings mocks base method.
func (m *MockRealtimeRepository) ListTriggerBindings(ctx context.Context, workspaceID, eventType, subjectType string, dependencyKeys []string) ([]domain.TriggerBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTriggerBindings", ctx, workspaceID, eventType, subjectType, dependencyKeys)
	ret0, _ := ret[0].([]domain.TriggerBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTriggerBindings indicates an expected call of ListTriggerBindings.
func (mr *MockRealtimeRepositoryMockRecorder) ListTriggerBindings(ctx, workspaceID, eventType, subjectType, dependencyKeys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTriggerBindings", reflect.TypeOf((*MockRealtimeRepository)(nil).ListTriggerBindings), ctx, workspaceID, eventType, subjectType, dependencyKeys)
}

// MarkOutboxPublished mocks base method.
func (m *MockRealtimeRepository) MarkOutboxPublished(ctx context.Context, workspaceID string, id, claimToken uuid.UUID, publishedAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxPublished", ctx, workspaceID, id, claimToken, publishedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOutboxPublished indicates an expected call of MarkOutboxPublished.
func (mr *MockRealtimeRepositoryMockRecorder) MarkOutboxPublished(ctx, workspaceID, id, claimToken, publishedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxPublished", reflect.TypeOf((*MockRealtimeRepository)(nil).MarkOutboxPublished), ctx, workspaceID, id, claimToken, publishedAt)
}

// ProcessRuleEvent mocks base method.
func (m *MockRealtimeRepository) ProcessRuleEvent(ctx context.Context, request domain.RuleProcessRequest) (domain.RuleProcessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRuleEvent", ctx, request)
	ret0, _ := ret[0].(domain.RuleProcessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRuleEvent indicates an expected call of ProcessRuleEvent.
func (mr *MockRealtimeRepositoryMockRecorder) ProcessRuleEvent(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRuleEvent", reflect.TypeOf((*MockRealtimeRepository)(nil).ProcessRuleEvent), ctx, request)
}

// ReleaseOutbox mocks base method.
func (m *MockRealtimeRepository) ReleaseOutbox(ctx context.Context, workspaceID string, id, claimToken uuid.UUID, availableAt time.Time, lastError string, dead bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseOutbox", ctx, workspaceID, id, claimToken, availableAt, lastError, dead)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseOutbox indicates an expected call of ReleaseOutbox.
func (mr *MockRealtimeRepositoryMockRecorder) ReleaseOutbox(ctx, workspaceID, id, claimToken, availableAt, lastError, dead interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseOutbox", reflect.TypeOf((*MockRealtimeRepository)(nil).ReleaseOutbox), ctx, workspaceID, id, claimToken, availableAt, lastError, dead)
}

// ReplaceTriggerBindings mocks base method.
func (m *MockRealtimeRepository) ReplaceTriggerBindings(ctx context.Context, workspaceID, automationID string, bindings []domain.TriggerBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTriggerBindings", ctx, workspaceID, automationID, bindings)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTriggerBindings indicates an expected call of ReplaceTriggerBindings.
func (mr *MockRealtimeRepositoryMockRecorder) ReplaceTriggerBindings(ctx, workspaceID, automationID, bindings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTriggerBindings", reflect.TypeOf((*MockRealtimeRepository)(nil).ReplaceTriggerBindings), ctx, workspaceID, automationID, bindings)
}

// ReserveSideEffect mocks base method.
func (m *MockRealtimeRepository) ReserveSideEffect(ctx context.Context, workspaceID string, execution domain.SideEffectExecution) (domain.SideEffectExecution, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveSideEffect", ctx, workspaceID, execution)
	ret0, _ := ret[0].(domain.SideEffectExecution)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReserveSideEffect indicates an expected call of ReserveSideEffect.
func (mr *MockRealtimeRepositoryMockRecorder) ReserveSideEffect(ctx, workspaceID, execution interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveSideEffect", reflect.TypeOf((*MockRealtimeRepository)(nil).ReserveSideEffect), ctx, workspaceID, execution)
}

// WriteMatchAudit mocks base method.
func (m *MockRealtimeRepository) WriteMatchAudit(ctx context.Context, workspaceID string, audit domain.MatchAudit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMatchAudit", ctx, workspaceID, audit)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMatchAudit indicates an expected call of WriteMatchAudit.
func (mr *MockRealtimeRepositoryMockRecorder) WriteMatchAudit(ctx, workspaceID, audit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMatchAudit", reflect.TypeOf((*MockRealtimeRepository)(nil).WriteMatchAudit), ctx, workspaceID, audit)
}

// MockWorkspaceCursorRepository is a mock of WorkspaceCursorRepository interface.
type MockWorkspaceCursorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceCursorRepositoryMockRecorder
}

// MockWorkspaceCursorRepositoryMockRecorder is the mock recorder for MockWorkspaceCursorRepository.
type MockWorkspaceCursorRepositoryMockRecorder struct {
	mock *MockWorkspaceCursorRepository
}

// NewMockWorkspaceCursorRepository creates a new mock instance.
func NewMockWorkspaceCursorRepository(ctrl *gomock.Controller) *MockWorkspaceCursorRepository {
	mock := &MockWorkspaceCursorRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspaceCursorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceCursorRepository) EXPECT() *MockWorkspaceCursorRepositoryMockRecorder {
	return m.recorder
}

// NextWorkspaceIDs mocks base method.
func (m *MockWorkspaceCursorRepository) NextWorkspaceIDs(ctx context.Context, cursorName string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextWorkspaceIDs", ctx, cursorName, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextWorkspaceIDs indicates an expected call of NextWorkspaceIDs.
func (mr *MockWorkspaceCursorRepositoryMockRecorder) NextWorkspaceIDs(ctx, cursorName, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextWorkspaceIDs", reflect.TypeOf((*MockWorkspaceCursorRepository)(nil).NextWorkspaceIDs), ctx, cursorName, limit)
}
