// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hengshu-credit/yaoguang-marketing/internal/domain (interfaces: CustomerService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/hengshu-credit/yaoguang-marketing/internal/domain"
)

// MockCustomerService is a mock of CustomerService interface.
type MockCustomerService struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerServiceMockRecorder
}

// MockCustomerServiceMockRecorder is the mock recorder for MockCustomerService.
type MockCustomerServiceMockRecorder struct {
	mock *MockCustomerService
}

// NewMockCustomerService creates a new mock instance.
func NewMockCustomerService(ctrl *gomock.Controller) *MockCustomerService {
	mock := &MockCustomerService{ctrl: ctrl}
	mock.recorder = &MockCustomerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerService) EXPECT() *MockCustomerServiceMockRecorder {
	return m.recorder
}

// GetCustomer mocks base method.
func (m *MockCustomerService) GetCustomer(arg0 context.Context, arg1 *domain.GetCustomerRequest) (*domain.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", arg0, arg1)
	ret0, _ := ret[0].(*domain.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockCustomerServiceMockRecorder) GetCustomer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockCustomerService)(nil).GetCustomer), arg0, arg1)
}

// ListCustomers mocks base method.
func (m *MockCustomerService) ListCustomers(arg0 context.Context, arg1 *domain.CustomerListRequest) (*domain.CustomerListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", arg0, arg1)
	ret0, _ := ret[0].(*domain.CustomerListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockCustomerServiceMockRecorder) ListCustomers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockCustomerService)(nil).ListCustomers), arg0, arg1)
}

// MergeCustomer mocks base method.
func (m *MockCustomerService) MergeCustomer(arg0 context.Context, arg1 *domain.CustomerMergeRequest) (*domain.CustomerMergeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeCustomer", arg0, arg1)
	ret0, _ := ret[0].(*domain.CustomerMergeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeCustomer indicates an expected call of MergeCustomer.
func (mr *MockCustomerServiceMockRecorder) MergeCustomer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeCustomer", reflect.TypeOf((*MockCustomerService)(nil).MergeCustomer), arg0, arg1)
}

// UpsertCustomer mocks base method.
func (m *MockCustomerService) UpsertCustomer(arg0 context.Context, arg1 *domain.UpsertCustomerRequest) (*domain.CustomerMutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCustomer", arg0, arg1)
	ret0, _ := ret[0].(*domain.CustomerMutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCustomer indicates an expected call of UpsertCustomer.
func (mr *MockCustomerServiceMockRecorder) UpsertCustomer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCustomer", reflect.TypeOf((*MockCustomerService)(nil).UpsertCustomer), arg0, arg1)
}

// UpsertCustomerBatch mocks base method.
func (m *MockCustomerService) UpsertCustomerBatch(arg0 context.Context, arg1 *domain.CustomerBatchUpsertRequest) (*domain.CustomerBatchUpsertResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCustomerBatch", arg0, arg1)
	ret0, _ := ret[0].(*domain.CustomerBatchUpsertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCustomerBatch indicates an expected call of UpsertCustomerBatch.
func (mr *MockCustomerServiceMockRecorder) UpsertCustomerBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCustomerBatch", reflect.TypeOf((*MockCustomerService)(nil).UpsertCustomerBatch), arg0, arg1)
}
