root = "."
tmp_dir = "/cache/notifuse-air"

[build]
  bin = "/cache/notifuse-bin/server"
  cmd = "go build -o /cache/notifuse-bin/server ./cmd/api"
  delay = 500
  exclude_dir = [
    ".git",
    "console",
    "data",
    "notification_center",
    "plans",
    "tmp",
    "vendor",
    "web_analytics_sdk/node_modules"
  ]
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = true
  follow_symlink = false
  include_dir = ["cmd", "config", "internal", "pkg", "web_analytics_sdk"]
  include_ext = ["go", "html", "js", "tmpl", "tpl"]
  include_file = ["go.mod", "go.sum"]
  kill_delay = "5s"
  poll = true
  poll_interval = 500
  send_interrupt = true
  stop_on_error = true

[log]
  main_only = false
  time = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
