server {
    listen 8080;
    server_name _;
    client_max_body_size 32m;

    location = /console {
        return 307 /console/;
    }

    location /console/ {
        alias /workspace/console/dist/;
        try_files $uri $uri/ /console/index.html;
    }

    location = /notification-center {
        return 307 /notification-center/;
    }

    location /notification-center/ {
        alias /workspace/notification_center/dist/;
        try_files $uri $uri/ /notification-center/index.html;
    }

    location / {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
    }
}
